### ISSUE TITLE
"'NoneType' object is not callable" when adding ldap database to django

### ISSUE THREAD

**Issue by rubinhozzz** [django-ldapdb/django-ldapdb#122]
Running django 1.11 and trying to connect to LDAP server by using django module ldapdb (django-ldapdb==0.8.0):

    DATABASES = {
    	'ldap': {
    		'ENGINE': 'ldapdb.backends.ldap',
    		'NAME': 'ldap://192.168.1.39/',
    	},
    	'default': {
    		'ENGINE': 'django.db.backends.postgresql_psycopg2', # Add 'postgresql_psycopg2', 'mysql', 'sqlite3' or 'oracle'.
    		'NAME': 'prot',                      # Or path to database file if using sqlite3.
    		'USER': 'prot',                      # Not used with sqlite3.
    		'PASSWORD': 'geheim',                  # Not used with sqlite3.
    		'HOST': 'localhost',                      # Set to empty string for localhost. Not used with sqlite3.
    		'PORT': '5432',                      # Set to empty string for default. Not used with sqlite3.
    	},
    }
    
    DATABASE_ROUTERS = ['ldapdb.router.Router']

However I get an error in the ldapdb code.

    Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f4ba61ff840>
    Traceback (most recent call last):
      File "/home/nfs/ruben/Projects/prot-zboss/venv/lib/python3.4/site-packages/django/utils/autoreload.py", line 227, in wrapper
        fn(*args, **kwargs)
      File "/home/nfs/ruben/Projects/prot-zboss/venv/lib/python3.4/site-packages/django/core/management/commands/runserver.py", line 125, in inner_run
        self.check(display_num_errors=True)
      File "/home/nfs/ruben/Projects/prot-zboss/venv/lib/python3.4/site-packages/django/core/management/base.py", line 359, in check
        include_deployment_checks=include_deployment_checks,
      File "/home/nfs/ruben/Projects/prot-zboss/venv/lib/python3.4/site-packages/django/core/management/base.py", line 346, in _run_checks
        return checks.run_checks(**kwargs)
      File "/home/nfs/ruben/Projects/prot-zboss/venv/lib/python3.4/site-packages/django/core/checks/registry.py", line 81, in run_checks
        new_errors = check(app_configs=app_configs)
      File "/home/nfs/ruben/Projects/prot-zboss/venv/lib/python3.4/site-packages/django/core/checks/model_checks.py", line 30, in check_all_models
        errors.extend(model.check(**kwargs))
      File "/home/nfs/ruben/Projects/prot-zboss/venv/lib/python3.4/site-packages/django/db/models/base.py", line 1284, in check
        errors.extend(cls._check_long_column_names())
      File "/home/nfs/ruben/Projects/prot-zboss/venv/lib/python3.4/site-packages/django/db/models/base.py", line 1699, in _check_long_column_names
        connection = connections[db]
      File "/home/nfs/ruben/Projects/prot-zboss/venv/lib/python3.4/site-packages/django/db/utils.py", line 212, in __getitem__
        conn = backend.DatabaseWrapper(db, alias)
      File "/home/nfs/ruben/Projects/prot-zboss/venv/lib/python3.4/site-packages/ldapdb/backends/ldap/base.py", line 187, in __init__
        super(DatabaseWrapper, self).__init__(*args, **kwargs)
      File "/home/nfs/ruben/Projects/prot-zboss/venv/lib/python3.4/site-packages/django/db/backends/base/base.py", line 96, in __init__
        self.client = self.client_class(self)
    TypeError: 'NoneType' object is not callable

**Comment by ikreb7** [comment]
Hello,

django-ldapdb supports only the version until Django 1.10. Does the error still exist with 1.10?

**Comment by rubinhozzz** [comment]
Thanks. That was the problem. For the time being, I will be using 1.10 then. I hope it gets working for 1.11 very soon.

**Comment by kwill** [comment]
Please reopen this issue, as Django 1.11 support is now planned (see #123).
