### ISSUE TITLE
Tests fails - PendingDeprecationWarning: the imp module is deprecated

### ISSUE THREAD

**Issue by ikreb7** [django-ldapdb/django-ldapdb#138]
The problem is the module `virtualenv` which `tox `uses. See: https://github.com/tox-dev/tox/issues/436

`python -Wdefault -Werror -Wignore::DeprecationWarning:site:165 manage_dev.py test
Traceback (most recent call last):
  File "manage_dev.py", line 9, in <module>
    from django.core.management import execute_from_command_line
  File "django-ldapdb/.tox/py34-django20/lib/python3.4/site-packages/django/__init__.py", line 1, in <module>
    from django.utils.version import get_version
  File "django-ldapdb/.tox/py34-django20/lib/python3.4/site-packages/django/utils/version.py", line 5, in <module>
    from distutils.version import LooseVersion
  File "django-ldapdb/.tox/py34-django20/lib/python3.4/distutils/__init__.py", line 4, in <module>
    import imp
  File "django-ldapdb/.tox/py34-django20/lib/python3.4/imp.py", line 32, in <module>
    PendingDeprecationWarning)
PendingDeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
`

**Comment by rbarrois** [comment]
A workaround has been added in 2a7d1363cb419657e77248f80bdfc30a65676635.
