### ISSUE TITLE
filtering using date and SQL/LDAP translation mistake

### ISSUE THREAD

**Issue by romain-dartigues** [django-ldapdb/django-ldapdb#149]
Filtering by dates fail with `ldap.FILTER_ERROR: {'desc': 'Bad search filter'}`.

## Example

With:
```python
class LDAPPeople(ldapdb.models.Model):
    base_dn = "ou=people,dc=example,dc=net"
    object_classes = ['posixAccount']
    fullname = ldapdb.models.fields.CharField(db_column='cn', max_length=200, primary_key=True)
    pwdChangedTime = DateTimeField(db_column='pwdChangedTime')
```

Trying to follow the processes:
```python
>>> import django.db, ldapdb.backends.ldap.compiler
>>> import example.people.models

>>> example.people.models.LDAPPeople.objects.filter(pwdChangedTime__gte='2018-01-01')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  [...]
  File "~/.virtualenvs/homepage/lib/python3.6/site-packages/ldap/ldapobject.py", line 313, in _ldap_call
    result = func(*args,**kwargs)
ldap.FILTER_ERROR: {'desc': 'Bad search filter'}

>>> connection = django.db.connections['ldap']
>>> qs = example.people.models.LDAPPeople.objects.filter(pwdChangedTime__gte='2018-01-01')
>>> compiler = ldapdb.backends.ldap.compiler.SQLCompiler(query=qs.query, connection=connection, using=None)
>>> ldapdb.backends.ldap.compiler.where_node_as_ldap(qs.query.where, compiler, connection)
('people_ldappeople.pwdChangedTime >= %s', ['2018-01-01'])
>>> [w.as_sql(compiler, connection) for w in qs.query.where.children]
[('people_ldappeople.pwdChangedTime >= %s', ['2018-01-01'])]
```

It seems that `ldapdb.backends.ldap.compiler.SQLCompiler` (through `django.db.models.lookup.BuiltinLookup.as_sql`?) prepend what would be the database name in SQL but is useless in the LDAP case.

Any idea on how to fix or workaround it?

Thanks.

**Comment by rbarrois** [comment]
Finally fixed! Thanks for the report :)
