### ISSUE TITLE
Regression on #175 with Django 3?

### ISSUE THREAD

**Issue by SwampFalc** [django-ldapdb/django-ldapdb#204]
#### Description
I'm trying to follow the instructions, which state that I should add a "primary_key=True" setting to a field. However, on Django 3.1, this results in an error.

##### Model code
```python
class DomainUser(models.Model):
    class Meta:
        ordering = ['last_name']
        verbose_name = 'Domain User'
        verbose_name_plural = 'Domain Users'

    # LDAP meta-data
    base_dn = 'OU=USERS,OU=FED,DC=feddom,DC=fedasil,DC=be'
    object_classes = [
        'top',
        "user",
        "person",
        'posixAccount',
        'organizationalPerson',
    ]

    cn = fields.CharField(db_column='cn', primary_key=True)
```

##### The issue
```python
$ python manage.py migrate
Operations to perform:
  Apply all migrations: domainmanager
Running migrations:
  Applying domainmanager.0001_initial...Traceback (most recent call last):
  File "/home/ldt/Projects/fedjango/.venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
  File "/home/ldt/Projects/fedjango/.venv/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 411, in execute
    return Database.Cursor.execute(self, query)
sqlite3.OperationalError: table "domainmanager_domainuser" has more than one primary key

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ldt/Projects/fedjango/manage.py", line 22, in <module>
    main()
  File "/home/ldt/Projects/fedjango/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ldt/Projects/fedjango/.venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/ldt/Projects/fedjango/.venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ldt/Projects/fedjango/.venv/lib/python3.9/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ldt/Projects/fedjango/.venv/lib/python3.9/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/home/ldt/Projects/fedjango/.venv/lib/python3.9/site-packages/django/core/management/base.py", line 85, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/ldt/Projects/fedjango/.venv/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 243, in handle
    post_migrate_state = executor.migrate(
  File "/home/ldt/Projects/fedjango/.venv/lib/python3.9/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/ldt/Projects/fedjango/.venv/lib/python3.9/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/ldt/Projects/fedjango/.venv/lib/python3.9/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/ldt/Projects/fedjango/.venv/lib/python3.9/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/ldt/Projects/fedjango/.venv/lib/python3.9/site-packages/django/db/migrations/operations/models.py", line 92, in database_forwards
    schema_editor.create_model(model)
  File "/home/ldt/Projects/fedjango/.venv/lib/python3.9/site-packages/django/db/backends/base/schema.py", line 324, in create_model
    self.execute(sql, params or None)
  File "/home/ldt/Projects/fedjango/.venv/lib/python3.9/site-packages/django/db/backends/base/schema.py", line 142, in execute
    cursor.execute(sql, params)
  File "/home/ldt/Projects/fedjango/.venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/home/ldt/Projects/fedjango/.venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/ldt/Projects/fedjango/.venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/ldt/Projects/fedjango/.venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/ldt/Projects/fedjango/.venv/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/ldt/Projects/fedjango/.venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
  File "/home/ldt/Projects/fedjango/.venv/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 411, in execute
    return Database.Cursor.execute(self, query)
django.db.utils.OperationalError: table "domainmanager_domainuser" has more than one primary key
```

#### Environment
- *Python version*: 3.9.6
- *LDAP server*: Samba 4.something
- *Operating system*: Ubuntu 20.04
- *Django*: 3.1
- *django-ldapdb*: 1.5.1

#### Notes
Looking at it, it seems it's actually SQLite that blocks the operation? So maybe it's not a regression on #175?

**Comment by SwampFalc** [comment]
For completeness' sake
**settings.py**
```python
ldap.set_option(ldap.OPT_REFERRALS, 0)
ldap.set_option(ldap.OPT_X_TLS_REQUIRE_CERT, 0)

DATABASES = {
    'ldap': {
        'ENGINE': 'ldapdb.backends.ldap',
        'NAME': 'ldaps://****.fedasil.be',
        'USER': 'cn=****,cn=users,dc=feddom,dc=fedasil,dc=be',
        'PASSWORD': ****,
    },
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
DATABASE_ROUTERS = ['ldapdb.router.Router']
```
